# Generated by Django 5.2.9 on 2026-03-18 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('path', models.CharField(max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThreatScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45, unique=True)),
                ('score', models.FloatField(db_index=True, default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_event', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('username', models.CharField(max_length=150)),
                ('success', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='django_secu_ip_addr_8aac17_idx'), models.Index(fields=['username', 'timestamp'], name='django_secu_usernam_d48bd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('location', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='django_security_monitor.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('event_type', models.CharField(choices=[('suspicious_path', 'Suspicious Path'), ('sensitive_file', 'Sensitive File Access'), ('brute_force', 'Brute Force Attack'), ('rate_limit', 'Rate Limit Exceeded'), ('sql_injection', 'SQL Injection'), ('xss_attempt', 'XSS Attempt'), ('path_traversal', 'Path Traversal'), ('scanner', 'Security Scanner'), ('auth_failure', 'Auth Failure'), ('csrf_failure', 'CSRF Failure'), ('honeypot', 'Honeypot Triggered'), ('403', '403 Forbidden'), ('404', '404 Not Found'), ('500', '500 Server Error'), ('blocked_ip', 'Blocked IP Attempt')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('payload', models.TextField(blank=True)),
                ('threat_score_delta', models.FloatField(default=0)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='django_secu_ip_addr_eba6e9_idx'), models.Index(fields=['event_type', 'timestamp'], name='django_secu_event_t_400e8f_idx'), models.Index(fields=['severity', 'timestamp'], name='django_secu_severit_bef673_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['ip_address'], name='django_secu_ip_addr_7e474a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['last_visit'], name='django_secu_last_vi_325448_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['timestamp'], name='django_secu_timesta_6c94c8_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path'], name='django_secu_path_843178_idx'),
        ),
    ]
